---
- name: Ansible patching playbook
  hosts: all
  tasks:
  
    - name: Install the latest patches from currently enabled repositories
      ansible.builtin.dnf:
        name: "*"
        update_only: yes
